### ISSUE TITLE
Auto arrange tutes algorithm?

### ISSUE THREAD

**Issue by pstefa1707** [pl4nty/anutimetable#123]
Thought I'd start a discussion in regards to implementing a feature to automatically select your tutes/workshop times. I always have trouble finding an optimal solution.

I know this project is still in development and working through teething bugs but could be a cool feature to think about, what algorithms could suit? I can look into implementation if it's decided a feature like this is feasible.

**Comment by jthvai** [comment]
I am extremely inclined to declare this out of scope because it would be quite demanding to implement, but @pl4nty opinions?
