### ISSUE TITLE
COMP3710 instances not showing

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#200]
COMP3710 Special Topics has 4 classes running this semester under the same course code, but they are different courses. Only one of them, Quantum Computing, is showing on this timetable.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by pl4nty** [comment]
This doesn't look to be an issue with Sem1 2023, but worth keeping open. Especially if we move to Allocate Plus

**Comment by jthvai** [comment]
Closing in favour of #513
