### ISSUE TITLE
student 

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#205]
the page remains loading and none of the courses will come up 

Label: none of the courses will load 

_Originally submitted by anonymous via the Microsoft Form_

**Comment by pl4nty** [comment]
The current datasource ([ANU Timetable Viewer](https://www.anu.edu.au/students/program-administration/timetabling/anu-timetable-viewer)) hasn't resolved via public DNS for 2 months. ANU comms say it should still be available though - maybe it's internal-only?

**Comment by pl4nty** [comment]
CraftyDH added 2023 data a little while ago, but we'll need to add a "last updated" element until automatic scraping is reestablished

**Comment by jthvai** [comment]
Fixed.
