### ISSUE TITLE
Background of Course Search remains white in Dark Mode (with white text due to dark mode, becoming unreadable)

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#211]
Reproduced in Firefox and Chrome on macOS Monterey, the issue is that when Dark Mode is enabled, the text color of the page changes to become white, but the background of the course search dropdown (#react-select-2-listbox) remains white, hence the search result course names are unreadable unless you hover over them.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by jthvai** [comment]
Closing as a duplicate, to be tracked in #219 (even though this issue came first).
