### ISSUE TITLE
The timetable is off by 1 hour, it needs to be adjusted to daylight savings

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#214]
For example, according the ANU MyTimetable planner, I have a class that starts at 2pm. But on this timetable, it says it starts at 1pm. This problem is consistent with all my classes so far.

Label: Issue

_Originally submitted by anonymous via the Microsoft Form_

**Comment by jthvai** [comment]
Cannot reproduce, likely a timezone config issue (Brisbane instead of Sydney).
