### ISSUE TITLE
Course Colours

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#269]
- super insignificant detail, but it would be great to not have super similar colours (eg light and slightly darker green :) ) for different courses please 

- a tangent to that, but it would be super cool if we could pick our own colours for courses in the timetable - even just a basic set of red, orange, yellow etc would be very neat (maths is purple and chem is dark blue, you can't convince me otherwise :) ) 

Label: Feature request

_Originally submitted by anonymous via the Microsoft Form_

**Comment by jthvai** [comment]
Duplicate of #108
