### ISSUE TITLE
class non existent (ARTV2607 Advanced Analogue Photography)

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#473]
This class: ARTV2607 Advanced Analogue Photography does not show up in time table.

Thank you. xx

Category: Issue
Contact: u7925833@anu.edu.au

_Originally submitted via the Microsoft Form_

**Comment by jthvai** [comment]
This course is available on both the old timetable and MyTimetable, and running the scraper has not fixed it.

**Comment by jthvai** [comment]
ARTV2607 now has events, and shows up.
