### ISSUE TITLE
Scale Issue for Save as PDF from Print 

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/anutimetable#502]
Category: Issue
Contact: 

_Originally submitted via the Microsoft Form_

**Comment by jthvai** [comment]
Confirmed.

Temporary workaround: print in landscape at 70% scale.

**Comment by jthvai** [comment]
This is what happens by default:

<details>
<summary>Screenshot of issue</summary>

![Screenshot of the Chromium print window, printing in portrait mode. The calendar only displays Sunday to Tuesday.](https://github.com/pl4nty/anutimetable/assets/49891202/3af88343-6e3d-4502-8d84-49242bb613b6)

</details>

**Comment by jthvai** [comment]
https://github.com/pl4nty/anutimetable/blob/3038ed365dce0df98646ab469e28c5620a7519d1/src/index.scss#L311-L314

The CSS is apparently already _supposed_ to print in landscape, though it clearly isn't.

**Comment by jthvai** [comment]
Well, side note: printing is entirely broken in Firefox (#503).
